[build]
  publish = "./"

[[redirects]]
  from = "https://www.traveltunisia.netlify.app/*"
  to = "https://traveltunisia.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://traveltunisia.netlify.app/*"
  to = "https://traveltunisia.netlify.app/:splat"
  status = 301
  force = true
